
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yahia
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
   
    private static class DatabaseConnector {
        private static final String URL = "jdbc:mysql://localhost:3306/login_db";
        private static final String USER = "root"; // Change to your MySQL username
        private static final String PASSWORD = "MYSQL"; // Change to your MySQL password

        public static Connection getConnection() throws SQLException, ClassNotFoundException {
            Class.forName("com.mysql.cj.jdbc.Driver");
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }   
        
    public login() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_layer = new javax.swing.JPanel();
        login_lable = new javax.swing.JLabel();
        username_lable = new javax.swing.JLabel();
        password_lable = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        password_field = new javax.swing.JPasswordField();
        username_field = new javax.swing.JTextField();
        shutdown_button = new javax.swing.JButton();
        sleep_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        background_layer.setMaximumSize(new java.awt.Dimension(506, 506));
        background_layer.setPreferredSize(new java.awt.Dimension(506, 506));
        background_layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_lable.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login_lable.setText("Login");
        background_layer.add(login_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        username_lable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username_lable.setText("Username");
        background_layer.add(username_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        password_lable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password_lable.setText("password");
        background_layer.add(password_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        login_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        background_layer.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 70, -1));

        password_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        background_layer.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 120, -1));

        username_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        background_layer.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, -1));

        shutdown_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power-button.png"))); // NOI18N
        shutdown_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shutdown_button.setMaximumSize(new java.awt.Dimension(32, 32));
        shutdown_button.setMinimumSize(new java.awt.Dimension(32, 32));
        shutdown_button.setPreferredSize(new java.awt.Dimension(32, 32));
        shutdown_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdown_buttonActionPerformed(evt);
            }
        });
        background_layer.add(shutdown_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        sleep_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleep_button.png"))); // NOI18N
        sleep_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        sleep_button.setMaximumSize(new java.awt.Dimension(32, 32));
        sleep_button.setMinimumSize(new java.awt.Dimension(32, 32));
        sleep_button.setPreferredSize(new java.awt.Dimension(32, 32));
        sleep_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleep_buttonActionPerformed(evt);
            }
        });
        background_layer.add(sleep_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_background.png"))); // NOI18N
        background_layer.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 510, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_layer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_layer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username = username_field.getText().trim();
        String password = new String(password_field.getPassword()).trim();

        // Validate input
        if (!validateLoginFields(username, password)) {
            return;
        }

        try {
            // Authenticate user (replace with your actual authentication logic)
            if (authenticateUser(username, password)) {
                // Record successful login
                saveLoginTime(username);

                // Open main application
                openMainApplication();
            } else {
                showErrorMessage("Invalid username or password", "Login Failed");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            showErrorMessage("Database Error: " + ex.getMessage(), "System Error");
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private boolean validateLoginFields(String username, String password) {
        if (username.isEmpty()) {
            showWarningMessage("Please enter your username", "Username Required");
            username_field.requestFocus();
            return false;
        }
        if (password.isEmpty()) {
            showWarningMessage("Please enter your password", "Password Required");
            password_field.requestFocus();
            return false;
        }
        return true;
    }

    private boolean authenticateUser(String username, String password) {
        // Replace this with your actual authentication logic
        // This is just a simple example
        return username.equals("a") && password.equals("a");
    }

    private void saveLoginTime(String username) throws SQLException, ClassNotFoundException {
        String sql = "INSERT INTO login_records (username, login_time) VALUES (?, ?)";

        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, username);
            pstmt.setTimestamp(2, new Timestamp(System.currentTimeMillis()));
            pstmt.executeUpdate();
        }
    }

    private void openMainApplication() {
        main application = new main();
        application.setVisible(true);
        this.dispose();
    }

    private void showWarningMessage(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.WARNING_MESSAGE);
    }

    private void showErrorMessage(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }
    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void shutdown_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdown_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_shutdown_buttonActionPerformed

    private void sleep_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleep_buttonActionPerformed
        // TODO add your handling code here:
        sleep sleep=new sleep();
        sleep.show();
        dispose();
    }//GEN-LAST:event_sleep_buttonActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel background_layer;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel login_lable;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_lable;
    private javax.swing.JButton shutdown_button;
    private javax.swing.JButton sleep_button;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_lable;
    // End of variables declaration//GEN-END:variables
}
