
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yahia
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroung_layer = new javax.swing.JPanel();
        shutdown_button = new javax.swing.JButton();
        sleep_button = new javax.swing.JButton();
        computer_button = new javax.swing.JButton();
        computer_label = new javax.swing.JLabel();
        network_button = new javax.swing.JButton();
        network_label = new javax.swing.JLabel();
        recycle_button = new javax.swing.JButton();
        recycle_label = new javax.swing.JLabel();
        calc_button = new javax.swing.JButton();
        calc_label = new javax.swing.JLabel();
        travel_button = new javax.swing.JButton();
        travel_label = new javax.swing.JLabel();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        backgroung_layer.setMaximumSize(new java.awt.Dimension(506, 506));
        backgroung_layer.setMinimumSize(new java.awt.Dimension(506, 506));
        backgroung_layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shutdown_button.setBackground(new java.awt.Color(255, 102, 102));
        shutdown_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power-button.png"))); // NOI18N
        shutdown_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shutdown_button.setMaximumSize(new java.awt.Dimension(32, 32));
        shutdown_button.setMinimumSize(new java.awt.Dimension(32, 32));
        shutdown_button.setPreferredSize(new java.awt.Dimension(32, 32));
        shutdown_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdown_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(shutdown_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        sleep_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleep_button.png"))); // NOI18N
        sleep_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        sleep_button.setMaximumSize(new java.awt.Dimension(32, 32));
        sleep_button.setMinimumSize(new java.awt.Dimension(32, 32));
        sleep_button.setPreferredSize(new java.awt.Dimension(32, 32));
        sleep_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleep_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(sleep_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        computer_button.setBackground(new java.awt.Color(204, 204, 204));
        computer_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer_main.png"))); // NOI18N
        computer_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        computer_button.setMaximumSize(new java.awt.Dimension(32, 32));
        computer_button.setMinimumSize(new java.awt.Dimension(32, 32));
        computer_button.setPreferredSize(new java.awt.Dimension(32, 32));
        computer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(computer_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        computer_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        computer_label.setText("My Computer");
        backgroung_layer.add(computer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        network_button.setBackground(new java.awt.Color(204, 204, 204));
        network_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network_main.png"))); // NOI18N
        network_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        network_button.setMaximumSize(new java.awt.Dimension(32, 32));
        network_button.setMinimumSize(new java.awt.Dimension(32, 32));
        network_button.setPreferredSize(new java.awt.Dimension(32, 32));
        network_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                network_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(network_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        network_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        network_label.setText("Network");
        backgroung_layer.add(network_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        recycle_button.setBackground(new java.awt.Color(204, 204, 204));
        recycle_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recycle_main.png"))); // NOI18N
        recycle_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        recycle_button.setMaximumSize(new java.awt.Dimension(32, 32));
        recycle_button.setMinimumSize(new java.awt.Dimension(32, 32));
        recycle_button.setPreferredSize(new java.awt.Dimension(32, 32));
        recycle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycle_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(recycle_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        recycle_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recycle_label.setText("Recycle Bin");
        backgroung_layer.add(recycle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        calc_button.setBackground(new java.awt.Color(204, 204, 204));
        calc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator_main.png"))); // NOI18N
        calc_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        calc_button.setMaximumSize(new java.awt.Dimension(32, 32));
        calc_button.setMinimumSize(new java.awt.Dimension(32, 32));
        calc_button.setPreferredSize(new java.awt.Dimension(32, 32));
        calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(calc_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        calc_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calc_label.setText("Calculator");
        backgroung_layer.add(calc_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        travel_button.setBackground(new java.awt.Color(204, 204, 204));
        travel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airplane_main.png"))); // NOI18N
        travel_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        travel_button.setMaximumSize(new java.awt.Dimension(32, 32));
        travel_button.setMinimumSize(new java.awt.Dimension(32, 32));
        travel_button.setPreferredSize(new java.awt.Dimension(32, 32));
        travel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travel_buttonActionPerformed(evt);
            }
        });
        backgroung_layer.add(travel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        travel_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        travel_label.setText("Travel");
        backgroung_layer.add(travel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        backgound.setMaximumSize(new java.awt.Dimension(506, 506));
        backgound.setMinimumSize(new java.awt.Dimension(506, 506));
        backgound.setPreferredSize(new java.awt.Dimension(506, 506));
        backgroung_layer.add(backgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroung_layer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroung_layer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shutdown_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdown_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_shutdown_buttonActionPerformed

    private void sleep_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleep_buttonActionPerformed
        // TODO add your handling code here:
        sleep sleep=new sleep();
        sleep.show();
        dispose();
    }//GEN-LAST:event_sleep_buttonActionPerformed

    private void computer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Depend on yourself?! \n Don't bother me", "Error!!!", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_computer_buttonActionPerformed

    private void network_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_network_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You are connected with internet", "Error!!!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_network_buttonActionPerformed

    private void calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Calc the cost to leave as fast as you can.", "Error!!!", JOptionPane.WARNING_MESSAGE);
        calc calc=new calc();
        calc.setVisible(true);
    }//GEN-LAST:event_calc_buttonActionPerformed

    private void recycle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycle_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "There is no trash , ARE YOU?!", "Error!!!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_recycle_buttonActionPerformed

    private void travel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travel_buttonActionPerformed
        // TODO add your handling code here:
        travel travel=new travel();
        travel.setVisible(true);
    }//GEN-LAST:event_travel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgound;
    private javax.swing.JPanel backgroung_layer;
    private javax.swing.JButton calc_button;
    private javax.swing.JLabel calc_label;
    private javax.swing.JButton computer_button;
    private javax.swing.JLabel computer_label;
    private javax.swing.JButton network_button;
    private javax.swing.JLabel network_label;
    private javax.swing.JButton recycle_button;
    private javax.swing.JLabel recycle_label;
    private javax.swing.JButton shutdown_button;
    private javax.swing.JButton sleep_button;
    private javax.swing.JButton travel_button;
    private javax.swing.JLabel travel_label;
    // End of variables declaration//GEN-END:variables
}
