/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yahia
 */
public class calc extends javax.swing.JFrame {
    
    String operator;
    double num1, num2, result;


    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_layer = new javax.swing.JPanel();
        dot_button = new javax.swing.JButton();
        zero_button = new javax.swing.JButton();
        one_button = new javax.swing.JButton();
        two_button = new javax.swing.JButton();
        three_button = new javax.swing.JButton();
        four_button = new javax.swing.JButton();
        five_button = new javax.swing.JButton();
        six_button = new javax.swing.JButton();
        seven_button = new javax.swing.JButton();
        eight_button = new javax.swing.JButton();
        nine_button = new javax.swing.JButton();
        plus_button = new javax.swing.JButton();
        subtrac_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        multiply_button = new javax.swing.JButton();
        equal_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        down_background = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        upper_background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background_layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dot_button.setBackground(new java.awt.Color(153, 153, 153));
        dot_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dot_button.setForeground(new java.awt.Color(255, 255, 255));
        dot_button.setText(".");
        dot_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dot_buttonActionPerformed(evt);
            }
        });
        background_layer.add(dot_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 40, 40));

        zero_button.setBackground(new java.awt.Color(153, 153, 153));
        zero_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zero_button.setForeground(new java.awt.Color(255, 255, 255));
        zero_button.setText("0");
        zero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_buttonActionPerformed(evt);
            }
        });
        background_layer.add(zero_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 40, 40));

        one_button.setBackground(new java.awt.Color(153, 153, 153));
        one_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        one_button.setForeground(new java.awt.Color(255, 255, 255));
        one_button.setText("1");
        one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_buttonActionPerformed(evt);
            }
        });
        background_layer.add(one_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 40));

        two_button.setBackground(new java.awt.Color(153, 153, 153));
        two_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        two_button.setForeground(new java.awt.Color(255, 255, 255));
        two_button.setText("2");
        two_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_buttonActionPerformed(evt);
            }
        });
        background_layer.add(two_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 40, 40));

        three_button.setBackground(new java.awt.Color(153, 153, 153));
        three_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        three_button.setForeground(new java.awt.Color(255, 255, 255));
        three_button.setText("3");
        three_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_buttonActionPerformed(evt);
            }
        });
        background_layer.add(three_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 40, 40));

        four_button.setBackground(new java.awt.Color(153, 153, 153));
        four_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        four_button.setForeground(new java.awt.Color(255, 255, 255));
        four_button.setText("4");
        four_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_buttonActionPerformed(evt);
            }
        });
        background_layer.add(four_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 40));

        five_button.setBackground(new java.awt.Color(153, 153, 153));
        five_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        five_button.setForeground(new java.awt.Color(255, 255, 255));
        five_button.setText("5");
        five_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_buttonActionPerformed(evt);
            }
        });
        background_layer.add(five_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 40, 40));

        six_button.setBackground(new java.awt.Color(153, 153, 153));
        six_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        six_button.setForeground(new java.awt.Color(255, 255, 255));
        six_button.setText("6");
        six_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_buttonActionPerformed(evt);
            }
        });
        background_layer.add(six_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 40, 40));

        seven_button.setBackground(new java.awt.Color(153, 153, 153));
        seven_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seven_button.setForeground(new java.awt.Color(255, 255, 255));
        seven_button.setText("7");
        seven_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_buttonActionPerformed(evt);
            }
        });
        background_layer.add(seven_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 40, 40));

        eight_button.setBackground(new java.awt.Color(153, 153, 153));
        eight_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eight_button.setForeground(new java.awt.Color(255, 255, 255));
        eight_button.setText("8");
        eight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_buttonActionPerformed(evt);
            }
        });
        background_layer.add(eight_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 40, 40));

        nine_button.setBackground(new java.awt.Color(153, 153, 153));
        nine_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nine_button.setForeground(new java.awt.Color(255, 255, 255));
        nine_button.setText("9");
        nine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_buttonActionPerformed(evt);
            }
        });
        background_layer.add(nine_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 40));

        plus_button.setBackground(new java.awt.Color(255, 153, 0));
        plus_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plus_button.setForeground(new java.awt.Color(255, 255, 255));
        plus_button.setText("+");
        plus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_buttonActionPerformed(evt);
            }
        });
        background_layer.add(plus_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 40, 40));

        subtrac_button.setBackground(new java.awt.Color(255, 153, 0));
        subtrac_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subtrac_button.setForeground(new java.awt.Color(255, 255, 255));
        subtrac_button.setText("-");
        subtrac_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrac_buttonActionPerformed(evt);
            }
        });
        background_layer.add(subtrac_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 40, 40));

        divide_button.setBackground(new java.awt.Color(255, 153, 0));
        divide_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divide_button.setForeground(new java.awt.Color(255, 255, 255));
        divide_button.setText("/");
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });
        background_layer.add(divide_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, 40));

        multiply_button.setBackground(new java.awt.Color(255, 153, 0));
        multiply_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        multiply_button.setForeground(new java.awt.Color(255, 255, 255));
        multiply_button.setText("*");
        multiply_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiply_buttonActionPerformed(evt);
            }
        });
        background_layer.add(multiply_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, 40));

        equal_button.setBackground(new java.awt.Color(51, 153, 0));
        equal_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        equal_button.setForeground(new java.awt.Color(255, 255, 255));
        equal_button.setText("=");
        equal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_buttonActionPerformed(evt);
            }
        });
        background_layer.add(equal_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 40, 40));

        clear_button.setBackground(new java.awt.Color(255, 0, 0));
        clear_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear_button.setForeground(new java.awt.Color(255, 255, 255));
        clear_button.setText("C");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        background_layer.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 40, 40));

        exit_button.setBackground(new java.awt.Color(255, 0, 0));
        exit_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit_button.setForeground(new java.awt.Color(255, 255, 255));
        exit_button.setText("Q");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        background_layer.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 40, 40));

        down_background.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout down_backgroundLayout = new javax.swing.GroupLayout(down_background);
        down_background.setLayout(down_backgroundLayout);
        down_backgroundLayout.setHorizontalGroup(
            down_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        down_backgroundLayout.setVerticalGroup(
            down_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        background_layer.add(down_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 300));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        background_layer.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 90));

        upper_background.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout upper_backgroundLayout = new javax.swing.GroupLayout(upper_background);
        upper_background.setLayout(upper_backgroundLayout);
        upper_backgroundLayout.setHorizontalGroup(
            upper_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        upper_backgroundLayout.setVerticalGroup(
            upper_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        background_layer.add(upper_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_layer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_layer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_buttonActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        operator = "+";
        jTextField1.setText("");
    }//GEN-LAST:event_plus_buttonActionPerformed

    private void zero_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_zero_buttonActionPerformed

    private void seven_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_seven_buttonActionPerformed

    private void eight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_eight_buttonActionPerformed

    private void nine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_nine_buttonActionPerformed

    private void dot_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_dot_buttonActionPerformed

    private void one_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_one_buttonActionPerformed

    private void two_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_two_buttonActionPerformed

    private void three_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_three_buttonActionPerformed

    private void four_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_four_buttonActionPerformed

    private void five_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_five_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_buttonActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        operator = "/";
        jTextField1.setText("");
    }//GEN-LAST:event_divide_buttonActionPerformed

    private void multiply_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiply_buttonActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
         operator = "*";
         jTextField1.setText("");
    }//GEN-LAST:event_multiply_buttonActionPerformed

    private void equal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_buttonActionPerformed
        // TODO add your handling code here:
            num2 = Double.parseDouble(jTextField1.getText());

        switch (operator) {
            case "+":
                result = num1 + num2;
                break;
            case "-":
                result = num1 - num2;
                break;
            case "*":
                result = num1 * num2;
                break;
            case "/":
                result = num1 / num2;
                break;
        }

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_equal_buttonActionPerformed

    private void subtrac_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtrac_buttonActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
         operator = "-";
         jTextField1.setText("");
    }//GEN-LAST:event_subtrac_buttonActionPerformed

    private void six_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_six_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background_layer;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton divide_button;
    private javax.swing.JButton dot_button;
    private javax.swing.JPanel down_background;
    private javax.swing.JButton eight_button;
    private javax.swing.JButton equal_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton five_button;
    private javax.swing.JButton four_button;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton multiply_button;
    private javax.swing.JButton nine_button;
    private javax.swing.JButton one_button;
    private javax.swing.JButton plus_button;
    private javax.swing.JButton seven_button;
    private javax.swing.JButton six_button;
    private javax.swing.JButton subtrac_button;
    private javax.swing.JButton three_button;
    private javax.swing.JButton two_button;
    private javax.swing.JPanel upper_background;
    private javax.swing.JButton zero_button;
    // End of variables declaration//GEN-END:variables
}
