
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
        
/**
 *
 * @author yahia
 */
public class travel extends javax.swing.JFrame {

    /**
     * Creates new form travel
     */
    
    private static class DatabaseConnector {
    private static final String URL = "jdbc:mysql://localhost:3306/travel_db";
    private static final String USER = "root"; // Change to your MySQL username
    private static final String PASSWORD = "MYSQL"; // Change to your MySQL password
    
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}
    public travel() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_travel = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        home_background = new javax.swing.JLabel();
        booking = new javax.swing.JPanel();
        head_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        typel_label = new javax.swing.JLabel();
        type_box = new javax.swing.JComboBox<>();
        phone_label = new javax.swing.JLabel();
        phone_field = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        gender_label = new javax.swing.JLabel();
        gender_box = new javax.swing.JComboBox<>();
        pass_label = new javax.swing.JLabel();
        pass_field = new javax.swing.JTextField();
        nation_label = new javax.swing.JLabel();
        nation_field = new javax.swing.JTextField();
        from_label = new javax.swing.JLabel();
        from_box = new javax.swing.JComboBox<>();
        to_label = new javax.swing.JLabel();
        to_box = new javax.swing.JComboBox<>();
        logo_label = new javax.swing.JLabel();
        book_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        booking_background = new javax.swing.JLabel();
        instracion = new javax.swing.JPanel();
        instraction_background = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        about_background = new javax.swing.JLabel();
        navigation = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        home_label = new javax.swing.JLabel();
        booking_label = new javax.swing.JLabel();
        instraction_label = new javax.swing.JLabel();
        about_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_travel.setBackground(new java.awt.Color(255, 255, 204));
        main_travel.setAutoscrolls(true);
        main_travel.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        main_travel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("With Our Flights");
        home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discover The World");
        home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2- Safety");
        home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3- Trust");
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1- Comfort");
        home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("Taameya Flight ");
        home.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 180));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GO Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        home.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, 30));

        home_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_travel.png"))); // NOI18N
        home.add(home_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        main_travel.addTab("Home", home);

        booking.setBackground(new java.awt.Color(255, 255, 255));
        booking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head_label.setBackground(new java.awt.Color(255, 255, 255));
        head_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        head_label.setText("Fill Information");
        booking.add(head_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        name_label.setBackground(new java.awt.Color(255, 255, 255));
        name_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label.setText("Full Name");
        booking.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        name_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booking.add(name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        typel_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        typel_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typel_label.setText("Ticket Type");
        booking.add(typel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 120, -1));

        type_box.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One-Way", "Round" }));
        booking.add(type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 280, 120, -1));

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phone_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phone_label.setText("Phone");
        booking.add(phone_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, -1));

        phone_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phone_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booking.add(phone_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, -1));

        email_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email_label.setText("Email");
        booking.add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 230, -1));

        email_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        email_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booking.add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, -1));

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender_label.setText("Gender");
        booking.add(gender_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 90, -1));

        gender_box.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        gender_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        booking.add(gender_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        pass_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_label.setText("Pass Number");
        booking.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, -1));

        pass_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booking.add(pass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, -1));

        nation_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nation_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nation_label.setText("Nationality");
        booking.add(nation_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, -1));

        nation_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nation_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booking.add(nation_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, -1));

        from_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        from_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        from_label.setText("From");
        booking.add(from_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, -1));

        from_box.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        from_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", "Alex", "Capital" }));
        booking.add(from_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, -1));

        to_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        to_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to_label.setText("To");
        booking.add(to_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, -1));

        to_box.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        to_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Madrid", "Medina", "Mecca", "Berlin", "Dubai", "Doha", "Riyadh", "Jeddah", "Marrakesh" }));
        booking.add(to_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, -1));

        logo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel_logo.png"))); // NOI18N
        booking.add(logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 230));

        book_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        book_button.setText("BOOK");
        book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_buttonActionPerformed(evt);
            }
        });
        booking.add(book_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        reset_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset_button.setText("RESET");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        booking.add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        booking_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_travel.png"))); // NOI18N
        booking.add(booking_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 470, 483));

        main_travel.addTab("Booking", booking);

        instracion.setBackground(new java.awt.Color(255, 255, 255));
        instracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instraction_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instructions_travel.png"))); // NOI18N
        instracion.add(instraction_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        main_travel.addTab("Instraction", instracion);

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        about.add(about_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 470, 483));

        main_travel.addTab("About", about);

        getContentPane().add(main_travel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -40, 470, 520));
        main_travel.getAccessibleContext().setAccessibleName("travel");
        main_travel.getAccessibleContext().setAccessibleDescription("");

        navigation.setBackground(new java.awt.Color(255, 204, 0));
        navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit_nave_travel.png"))); // NOI18N
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton2.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        navigation.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel_logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        navigation.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 157));

        home_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_nave_travel.png"))); // NOI18N
        home_label.setText("Home ->");
        home_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_labelMouseClicked(evt);
            }
        });
        navigation.add(home_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 168, 55));

        booking_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        booking_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket_nave_travel.png"))); // NOI18N
        booking_label.setText("Booking ->");
        booking_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_labelMouseClicked(evt);
            }
        });
        navigation.add(booking_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 248, 168, 55));

        instraction_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instraction_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instruction_nave_travel.png"))); // NOI18N
        instraction_label.setText("Instraction ->");
        instraction_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instraction_labelMouseClicked(evt);
            }
        });
        navigation.add(instraction_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, 168, 55));

        about_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_nave_travel.png"))); // NOI18N
        about_label.setText("About Us ->");
        about_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_labelMouseClicked(evt);
            }
        });
        navigation.add(about_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 168, 55));

        getContentPane().add(navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_labelMouseClicked
        // TODO add your handling code here:
        main_travel.setSelectedIndex(0);
    }//GEN-LAST:event_home_labelMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        main_travel.setSelectedIndex(0);
    }//GEN-LAST:event_logoMouseClicked

    private void booking_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_labelMouseClicked
        // TODO add your handling code here:
        main_travel.setSelectedIndex(1);
    }//GEN-LAST:event_booking_labelMouseClicked

    private void instraction_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instraction_labelMouseClicked
        // TODO add your handling code here:
        main_travel.setSelectedIndex(2);
    }//GEN-LAST:event_instraction_labelMouseClicked

    private void about_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseClicked
        // TODO add your handling code here:
        main_travel.setSelectedIndex(3);
    }//GEN-LAST:event_about_labelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        main_travel.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void book_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_buttonActionPerformed
        // TODO add your handling code here:
        // Validate all required fields
    if (!validateFields()) {
        return;
    }
    
    try {
        // Calculate ticket price
        double price = calculateTicketPrice();
        
        // Get current timestamp
        Timestamp bookingTime = new Timestamp(System.currentTimeMillis());
        
        // Save to database
        saveBooking(price, bookingTime);
        
        // Show confirmation
        showConfirmation(price);
        
        // Reset form
        resetForm();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Database Error: " + ex.getMessage(), 
            "Booking Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + ex.getMessage(), 
            "Booking Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_book_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:                                       
        resetForm();
    }//GEN-LAST:event_reset_buttonActionPerformed

    private boolean validateFields() {
    if (name_field.getText().trim().isEmpty()) {
        showWarning("Please enter your full name", "Name Required");
        return false;
    }
    if (email_field.getText().trim().isEmpty() || !isValidEmail(email_field.getText().trim())) {
        showWarning("Please enter a valid email address", "Email Required");
        return false;
    }
    if (phone_field.getText().trim().isEmpty() || !phone_field.getText().trim().matches("\\d+")) {
        showWarning("Please enter a valid phone number (digits only)", "Phone Required");
        return false;
    }
    if (nation_field.getText().trim().isEmpty()) {
        showWarning("Please enter your nationality", "Nationality Required");
        return false;
    }
    if (pass_field.getText().trim().isEmpty()) {
        showWarning("Please enter your passport number", "Passport Required");
        return false;
    }
    return true;
}

private boolean isValidEmail(String email) {
    return email.matches("^[\\w-.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
}

private void showWarning(String message, String title) {
    JOptionPane.showMessageDialog(this, message, title, JOptionPane.WARNING_MESSAGE);
}

private double calculateTicketPrice() {
    String destination = to_box.getSelectedItem().toString();
    String type = type_box.getSelectedItem().toString();
    
    // Base prices
    double price;
    switch (destination) {
        case "London":
        case "Berlin":
            price = 500.0;
            break;
        case "Madrid":
        case "Dubai":
        case "Doha":
            price = 450.0;
            break;
        case "Mecca":
        case "Medina":
        case "Jeddah":
        case "Riyadh":
            price = 400.0;
            break;
        case "Marrakesh":
            price = 350.0;
            break;
        default:
            price = 300.0;
    }
    
    // Round trip costs more
    if (type.equals("Round")) {
        price *= 1.8;
    }
    
    return price;
}

private void saveBooking(double price, Timestamp bookingTime) throws SQLException {
    String sql = "INSERT INTO bookings (name, email, phone, nationality, passport, gender, "
            + "departure_from, destination, ticket_type, booking_time, price) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    try (Connection conn = DatabaseConnector.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, name_field.getText().trim());
        pstmt.setString(2, email_field.getText().trim());
        pstmt.setString(3, phone_field.getText().trim());
        pstmt.setString(4, nation_field.getText().trim());
        pstmt.setString(5, pass_field.getText().trim());
        pstmt.setString(6, gender_box.getSelectedItem().toString());
        pstmt.setString(7, from_box.getSelectedItem().toString());
        pstmt.setString(8, to_box.getSelectedItem().toString());
        pstmt.setString(9, type_box.getSelectedItem().toString());
        pstmt.setTimestamp(10, bookingTime);
        pstmt.setDouble(11, price);
        
        pstmt.executeUpdate();
    }
}

private void showConfirmation(double price) {
    String ref = generateBookingReference();
    String message = String.format(
        "<html><div style='text-align: center;'>"
        + "<h2>Booking Confirmed!</h2>"
        + "<p>Thank you for choosing Taameya Flight</p>"
        + "<p><strong>Total Cost:</strong> $%.2f</p>"
        + "<p>Confirmation sent to: %s</p>"
        + "<p>Booking Reference: %s</p>"
        + "</div></html>",
        price, email_field.getText().trim(), ref
    );
    
    JOptionPane.showMessageDialog(
        this, 
        message, 
        "Booking Success", 
        JOptionPane.INFORMATION_MESSAGE
    );
}

private String generateBookingReference() {
    return "TAM-" + System.currentTimeMillis();
}

private void resetForm() {
    name_field.setText("");
    email_field.setText("");
    phone_field.setText("");
    nation_field.setText("");
    pass_field.setText("");
    gender_box.setSelectedIndex(0);
    from_box.setSelectedIndex(0);
    to_box.setSelectedIndex(0);
    type_box.setSelectedIndex(0);
    name_field.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new travel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about;
    private javax.swing.JLabel about_background;
    private javax.swing.JLabel about_label;
    private javax.swing.JButton book_button;
    private javax.swing.JPanel booking;
    private javax.swing.JLabel booking_background;
    private javax.swing.JLabel booking_label;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JComboBox<String> from_box;
    private javax.swing.JLabel from_label;
    private javax.swing.JComboBox<String> gender_box;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel head_label;
    private javax.swing.JPanel home;
    private javax.swing.JLabel home_background;
    private javax.swing.JLabel home_label;
    private javax.swing.JPanel instracion;
    private javax.swing.JLabel instraction_background;
    private javax.swing.JLabel instraction_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo_label;
    private javax.swing.JTabbedPane main_travel;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField nation_field;
    private javax.swing.JLabel nation_label;
    private javax.swing.JPanel navigation;
    private javax.swing.JTextField pass_field;
    private javax.swing.JLabel pass_label;
    private javax.swing.JTextField phone_field;
    private javax.swing.JLabel phone_label;
    private javax.swing.JButton reset_button;
    private javax.swing.JComboBox<String> to_box;
    private javax.swing.JLabel to_label;
    private javax.swing.JComboBox<String> type_box;
    private javax.swing.JLabel typel_label;
    // End of variables declaration//GEN-END:variables
}
